name: Python Package

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check docker installed or not
      run: docker run hello-world
    - name: Push to docker hub
      uses: docker/build-push-action/@v1
      with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKERHUB_REPO}}
          tag_with_ref: true
    
